### ISSUE TITLE
Allow shadowing of inherited functions 

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aesophia#1]
@hanssv asked [here](https://github.com/aeternity/protocol/blob/master/contracts/sophia.md) if we want to allow overriding of inherited functions and whether there are some use cases for that. Solidity supports shadowing, which allows to extend logic of super critical functions without touching their code. 
To the outside world, especially if the contract follows a standard, the function with the extended logic remains the one to be called, there is no other.

Example (pseudocode)
```
contract basicToken {


    function transfer(amount, recipient) returns (bool) {
     *critical code here*
    }

}

contract myFancyToken is basicToken{


function transfer (amount, recipient) {
    doSomething();
    bool result = super.transfer(amount, recipient); // executing basicToken's transfer() logic and evaluating output!

    if (!result) damnItFailed();
        else
    doSomethingFancy();
}
```

only `myFancyToken`'s implementation of transfer() is accessible from the outside and gets called by default from every ERC20-able wallet/software/whatever, and the additional code of the dapp's smart contract utilizing this token gets executed automatically with every transfer.

If you need any "real" examples from production cases, drop a line :)

**Comment by hanssv** [comment]
Superseded by #198
