### ISSUE TITLE
Undecidable type inference crashes compilation

### ISSUE THREAD

**Issue by radrow** [aeternity/aesophia#108]
Compiling following code
```
contract Bum =
  stateful entrypoint bum() =
    Oracle.register(Contract.address, 12345, RelativeTTL(1000))
    ()
```
leads to internal compiler error (`{badmatch,undefined}`), however 
```
contract Bum =
  stateful entrypoint bum() =
    Oracle.register(Contract.address, 12345, RelativeTTL(1000)) : oracle(int, int)
    ()
```
works flawlessly.

The type infer cannot deduce return type of `Oracle.register...` because it is polymorphic and does not depend on the context. This causes oracle type to be specified by an unbound typevar which makes compiler mad. Inferred return type of `Oracle.register` is exactly
```
{app_t,
         [{origin,system}],
         {id,[{origin,system}],"oracle"},
         [{tvar,[{file,"xd"},{line,3},{col,5}],"'a"},
          {tvar,[{file,"xd"},{line,3},{col,5}],"'b"}]}}
```

We should detect such situations and raise type errors.

Bug copyright (c) @hanssv

**Comment by hanssv** [comment]
This is fixed already.
