### ISSUE TITLE
More functions on strings

### ISSUE THREAD

**Issue by UlfNorell** [aeternity/aesophia#176]
Some suggestions
```
  String.split(i : int, s : string) : string * string
  String.to_list(s : string) : list(char)
  String.from_list(cs : list(char)) : string
  String.at(s : string, i : int) : char
```
cc @thepiwo @radrow

**Comment by radrow** [comment]
May be also useful:
```
Char.to_int : char -> int
Char.from_int : int -> option?(char) 
```

**Comment by hanssv** [comment]
Maybe `String.contains`, etc.

**Comment by maptuhec** [comment]
Also useful:

```
String.to_upper_case 
String.to_lower_case
```

**Comment by maptuhec** [comment]
`String.to_bytes`?

**Comment by UlfNorell** [comment]
> `String.to_bytes`

What type would that have?

**Comment by maptuhec** [comment]
This was a suggestion from @hanssv for the following issue. The ecrecover returns. bytes, and if you want to compare it to a string it will not be possible for now(Bytes.to_str  returns uppercase String) if the string is not passed in uppercase. So probably the type should be bytes. Just an issue that we have run into today.

Best,
Martin

**Comment by UlfNorell** [comment]
The problem is that `bytes` have fixed length and you don't know the length of the string at compile time.

There could be a `Bytes.to_raw_string : bytes(n) => string` (or some better name) though, that gives you the bytes as they are with out hex-encoding.

I'm confused as to why you would have your address as an unencoded string though. It would contain lots of unprintable characters.

**Comment by tolbrino** [comment]
Something like `String.to_int(s : string) : int` would also be helpful.

**Comment by tolbrino** [comment]
And `String.tokens(s : string, c : char) : list(string)` would split the string into tokens with the given character used as limiter.

**Comment by radrow** [comment]
@tolbrino `String.to_int(s : string) : option(int)`, let's be safe

**Comment by radrow** [comment]
I just hope that the strings won't become a bad replacement for ADTs

**Comment by hanssv** [comment]
Maybe even `String.to_int(s : string, base : int) : option(int)`?
