### ISSUE TITLE
New VM-function to lookup the TTL of a name - AENS.expire_by(name : string) : option(int)

### ISSUE THREAD

**Issue by hanssv** [aeternity/aesophia#179]
To be able to handle name extensions in a contract it might be interesting to look up the current expiry (block height).

**Comment by hanssv** [comment]
+ also consider Oracle TTL?!

**Comment by marc0olo** [comment]
just asked a question related to this in the forum (https://forum.aeternity.com/t/aens-marketpace-example-sophia-python/5574/3?u=marc0olo).

is it planned to implement this together with #188?

I think this method alone is not enough to build a reliable marketplace for AENS names. both together should provide all required functionalities for building a marketplace.

**Comment by hanssv** [comment]
Yes, it makes sense to add these functions at the same time - it means adding a couple of lines in three (or four) different places so adding multiple things at the same time makes sense.
