### ISSUE TITLE
Function modifiers

### ISSUE THREAD

**Issue by UlfNorell** [aeternity/aesophia#195]
*From the Sophia discussion at the Sofia workshop.*

Solidity lets you create modifiers that can wrap function bodies in arbitrary code.

**Comment by UlfNorell** [comment]
Currently you can achieve this as
```
    function modifier(margs, body : () => 'a) : T('a) =
      stuff .. body() .. more_stuff

    function my_fun(args) =
      modifier(margs, () => body(args))
```
We could conceivably add some nicer syntax for applying the modifier.

What modifiers are people interested in using? The Solidity documentation has `priced`, `owned`, and `noReentrancy`. The latter is not needed in Sophia and the first two are simple `require` checks at the top of the function. It's not obvious that adding special syntax for this is worthwhile.

**Comment by nikita-fuchs** [comment]
Modifiers are highly useful in cases where you want to restrict the access to some functions to a specific set of users. E.g. 5 functions of the contract shall be only accessible if the user is "Rank A", owns a certain amount of value/tokens and also paid something to actually call this function. It makes a contract safer, smaller and more readable not to have to include all this logic multiple times everywhere.

**Comment by UlfNorell** [comment]
> not to have to include all this logic multiple times everywhere

You are allowed to not copy-paste code even without special syntax for modifiers.

The only the difference is between (imaginary syntax)
```sophia
@mustBeRankA()
entrypoint foo(...) =
  bla
```
and
```sophia
entrypoint foo(...) =
  mustBeRankA()
  bla
```

**Comment by nikita-fuchs** [comment]
Almost, as a modifier _wraps_ the function call, right now it would be something like 

```
entrypoint foo(params) =
  performChecks(params)
  ...function body...
  tidyUpAfterwards(params)
```
I forgot to mention the last part - sometimes you put sanity checks to double-check the outcome into the modifier or/and add some additional automation, which one might forget to perform when needing to add manually to function's end. If sophia improvements are decided to be done anyway, modifiers would be really nice, as they used to come really handy for not forgetting to implement safety checks in the past. Is the decorator syntax the one you'd propose, Ulf ? (I have no strong opinion here)

**Comment by UlfNorell** [comment]
That's why I asked for use cases which aren't simple access checks. What is a concrete example of `tidyUpAfterwards(..)`?

**Comment by UlfNorell** [comment]
Closing for now. Reopen if needed with actual use cases.
