### ISSUE TITLE
Pattern matching in function heads

### ISSUE THREAD

**Issue by UlfNorell** [aeternity/aesophia#196]
*From the Sophia discussion at the Sofia workshop.*

**Comment by UlfNorell** [comment]
The current syntax (mixing left-hand sides and type signatures) is not well suited for this. We could imagine allowing separate type signatures and multiple clauses:
```
  entrypoint
    foo : (int, string) => string
    foo(0, s) = s
    foo(n, s) = foo(n - 1, String.concat(s, s))
```

**Comment by radrow** [comment]
I love this

**Comment by nikita-fuchs** [comment]
I sense a strong smell of erlang in here - wouldn't this defacto lever out all strict type checking and allow for fallback functions taking whatever data ?

**Comment by UlfNorell** [comment]
What, no! Why would you think this would change the type system? The above is the same as
```sophia
entrypoint foo(a : int, s : string) =
  switch(a)
    0 => s
    n => foo(n - 1, String.concat(s, s)
```
