### ISSUE TITLE
FATE debugger

### ISSUE THREAD

**Issue by UlfNorell** [aeternity/aesophia#201]
*From the Sophia discussion at the Sofia workshop.*

**Comment by UlfNorell** [comment]
Two (orthogonal) things:
- Linking byte code and source code.
- Debugger for FATE byte code with stepping and breakpoints.

Could be added to https://github.com/aeternity/aerepl

**Comment by thepiwo** [comment]
I'd somehow like to see a http interface as long as we are not able to run aesophia in the browser, so people can build dev tools around

**Comment by nikita-fuchs** [comment]
It would be (very!) nice to have stepping and real time values of vars and state (to a not-so-crazy deep degree, I know it can get messy with nested maps etc.), as our contract language is way more complex than e.g. solidity. It would be really useful to see the success / return data of a remote contract call, too. Maybe there is a cheap way to achieve all this, by disabling the optimizer, therefore allow for higher gas limits in such special types of circumstances, and do this the classical way such things are always done ?

**Comment by radrow** [comment]
Since there is already an endeavor to do it, I am closing this issue for the sake of different minor steps that will lead us to a full-blown debugger. Watch aesophia, aeternity and aerepl for the progress.
