### ISSUE TITLE
Runtime validation of contracts

### ISSUE THREAD

**Issue by UlfNorell** [aeternity/aesophia#203]
Checking at runtime that a given contract indeed implements the expected interface.

**Comment by UlfNorell** [comment]
Note that such a check would give you no protection against malicious contracts, and would only be a(n expensive) sanity check ruling out silly mistakes.

**Comment by nikita-fuchs** [comment]
I've always been a little sceptical towards these interface checking endeavours, because people tend to believe in what they see - contracts then can easily pretend to do something that they actually won't, to say the least. It's a great feature for a general quick check, but the docs would need to read big warning signs here.

**Comment by thepiwo** [comment]
@UlfNorell could you give an example of what issues this would catch?

**Comment by UlfNorell** [comment]
Technically, what would be possible (but moderately expensive) is to check that there is a contract at a given address with a given set of entrypoints of expected types. However, contracts can lie about their types and a crash due to a missing entrypoint looks the same as a crash inside that entrypoint, so the only protection would be against people giving you bad contracts by accident.

I think a better feature would be to let you recover from failing contract calls using some try/catch mechanism. That would let you protect yourself also from malicious contracts, and would be much cheaper.

**Comment by nikita-fuchs** [comment]
This is a really useful thing. I favor the try-catch approach as a leach solution, although the first one would also have its benefits.

**Comment by UlfNorell** [comment]
Can you elaborate on the benefits of the first suggestion?

**Comment by UlfNorell** [comment]
The solution we settled on is adding *protected calls*. If
```sophia
contract Remote =
  entrypoint foo : int => int
```

Then for `r : Remote`
```sophia
r.foo(19) : int  // as before
r.foo(protected = true, 19) : option(int)
```
If the remote call fails for any reason (the contract doesn't exist/doesn't have `foo`, or `foo` has the wrong type, or crashes/runs out of gas, etc.) the protected call returns `None`.
