### ISSUE TITLE
FundMe Contract - sophia.md

### ISSUE THREAD

**Issue by emmanuelJet** [aeternity/aesophia#248]
```
type_error: Unbound variable raw_spend at line 13, column 5
At: Line 13, column 5
```
The error above was found when deploying the crowd-funding contract

**Comment by radrow** [comment]
Hi, could you attach a link to the source?

**Comment by emmanuelJet** [comment]
https://github.com/aeternity/aesophia/blob/lima/docs/sophia.md#examples

**Comment by radrow** [comment]
Thanks for the catch! It should work after #249
