### ISSUE TITLE
Generating random numbers

### ISSUE THREAD

**Issue by unboxedtype** [aeternity/aesophia#269]
It is well-known fact that blockchain transactions must be deterministic thus
a virtual machine must not emit any randomness into a contract execution.
However, several solutions for other blockchains  were proposed to mimic 
randomness, like using block numbers, mining time, oracles, etc.

Are there any suggested way to get randomness using Sophia language? 
Maybe you will find appropriate to include any hints regarding this question
into the manual.

**Comment by hanssv** [comment]
I would suggest using one of the hash functions and then convert to an integer:
```
let rand = Bytes.to_int(Crypto.blake2b(something_pseudo_random))
```
Where you could use a block-hash or something as `something_pseudo_random`

**Comment by unboxedtype** [comment]
Thanks, I will try it when they repair that annoying negative numbers issue.

Should I close this issue or you left it open intentionally?

**Comment by radrow** [comment]
I think this should be closed, as the proposed solution is so simple that it doesn't require writing any library or extending the language. However this is a nice trick, could be eternalized somewhere
