### ISSUE TITLE
Option to point out the record name during construction

### ISSUE THREAD

**Issue by radrow** [aeternity/aesophia#274]
It would be better if the user could refer which record are they constructing
```
record r{a : int, b : bool}
function f() : r = r{a = 2, b = true}
```
At this point this can be achieved by adding a type annotation `{a = 2, b = true} : r`, but this syntax is much less natural.

**Comment by UlfNorell** [comment]
That's already valid syntax and means updating the record `r` with new values for `a` and `b`. Overloading this syntax seems like it would lead to lots of confusion.

**Comment by radrow** [comment]
I can agree after some thoughts
