### ISSUE TITLE
Call result decoder does not perform type inference

### ISSUE THREAD

**Issue by gorbak25** [aeternity/aesophia#281]
When decoding call results we are not doing any type inference.
Given this contract:
```
contract Test = 
    entrypoint test(a: 'a) = a
```
By trying to call:
test(ak_11111111111111111111111111111111273Yts)
the resulting call result fails to decode:
```
Data error:
Cannot translate FATE value {address,<<0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
                                       0,0,0,0,0,0,0,0,0,0,0,0,0>>}
  of Sophia type 'a
```

**Comment by gorbak25** [comment]
~/aesophia_cli/priv/bin/v4.3.1/aesophia_cli Polymorphic.aes --call_result_type "ok" --call_result_fun "test" --call_result "cb_nwCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQeQRm"

**Comment by hanssv** [comment]
While you can do something about this in a few obvious cases; it can't be solved in the general case I think?!
