### ISSUE TITLE
Wrong error for event definition

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aesophia#302]
For 
```
    datatype event =
      Event1(indexed string, string)
```

I get `type_error: The event constructor Event1 (at line 4, column 7) has too many non-indexed values (max 1)``

whereas the docs say you can also have 0 non-indexed values of course. The correct error reason here is the `index`ing of a string.

**Comment by hanssv** [comment]
There are two errors on that line: 
* too many non-indexed values
* trying to index a string value

The first is an error of the event itself, i.e. at column 7, the second is a problem of the first field of the the event, i.e. at column 14. The errors are sorted in order of appearance, thus you get this one. Both errors are reported.
