### ISSUE TITLE
Polymorphism support (Must implement function if included an interface)

### ISSUE THREAD

**Issue by genievot** [aeternity/aesophia#307]
Greetings, 

I was wondering if there is a way to implement interfaces in Sophia so we can work on standards in a more appropriate way. As discussed here https://forum.aeternity.com/t/how-to-write-interfaces-in-sophia/8236/6 .

Best,

**Comment by radrow** [comment]
I see it as something like 
```
contract interface Strokable =
  entrypoint stroke : () => unit

contract Cat : Strokable =
  @impl 
  entrypoint stroke() = abort("not today")
```
or even
```
contract Cat =
  impl Strokable =
    entrypoint stroke() = abort("not today")
  entrypoint ...
```

The question is how deep do we want to dive into it:
- Do we want to let interfaces be subinterfaces of the others (smell Java)
- What about multiple inheritance?
- Should the type system treat it in Rust/Haskellish way as a typeclass or in OOP manner with subtyping?

**Comment by genievot** [comment]
Thank you for looking into it, My view on your questions:

-> I was not sure about this but could be helpful in the case of extended standards (Including a function that was not in the original interface, for e.g. adding `safeTransfer` if not in default ERC721) so should result in a cleaner code & better understanding.
-> Not sure If I currently have any use of this either but in the future, this might be helpful in writing cleaner modules (classes) and not deriving every class before moving on (Since you asked so I assume that currently, Sophia does not support multiple inheritance).
-> Not sure about this but whatever you prefer I can adapt to it.

Best,

**Comment by marc0olo** [comment]
I personally like this kind of style better:
```
contract interface Strokable =
  entrypoint stroke : () => unit

contract Cat : Strokable =
  @impl 
  entrypoint stroke() = abort("not today")
```

whereas the compilation should fail if the implementation of `stroke()` is missing in the contract.

- we should definitely provide multiple inheritance for interfaces
- subinterfaces would be great but I don't know whether this is a bit contrary to the current state of Sophia where we don't have contract inheritance (https://github.com/aeternity/aesophia/issues/198)
   - this should probably be introduced together
- I have no preference in regards to the type system, but probably the rust/haskell way fits Sophia better

**Comment by arpunk** [comment]
I might be biased, but what about:

```
interface Strokable =
  callback stroke : () => unit

interface Other =
  callback other : () => unit

contract Cat =
  @impl Strokable
  entrypoint stroke() = abort("not today")
  
  @impl Other
  entrypoint other() = about("probably tomorrow")
```

As for the questions:

> Do we want to let interfaces be subinterfaces of the others (smell Java)

I think this will lead to many layered interfaces. Probably keeping it flat enforces better callback design.

> What about multiple inheritance?

It would be nice if the compiler warns on missing entrypoints, specially if I plan to expand on a set of contracts/interfaces/behaviours/etc.

**Comment by radrow** [comment]
This is going to be extremely helpful with the upcoming contract factories

**Comment by marc0olo** [comment]
is there a plan to address this issue? @hanssv @ghallak

**Comment by hanssv** [comment]
I don't know of any plans. It is two rather big pieces of work and I'm not sure it is the best bang for the buck but it would be nice to have for sure ;-)

**Comment by marc0olo** [comment]
at least there were requests from the community in that regards in the past. what are more important issues in your opinion right now? just wondering :-)

would definitely be good to have these features

**Comment by radrow** [comment]
Note that you can hack it out by making unsafe contract coercions. Just deploy an identity contract and declare it as desired cast in your main contract. Then you can remote call it whenever you need dynamic casting.

This is dirty, but could serve as a polymorphism replacement until it is done.

**Comment by marc0olo** [comment]
> Note that you can hack it out by making unsafe contract coercions. Just deploy an identity contract and declare it as desired cast in your main contract. Then you can remote call it whenever you need dynamic casting.
> 
> This is dirty, but could serve as a polymorphism replacement until it is done.

That sounds interesting, but I guess we can wait for the final solution here. We should stop working around everything IMO :)

But definitely good to know if somebody wants to try it like you described.

**Comment by ghallak** [comment]
**Proposal 1**: Write the implementations along other functions, but precede implementations with `@impl` and declare that the contract implements the interface.

```
contract interface Strokable =
  entrypoint stroke : () => unit

contract Cat : Strokable =
  @impl entrypoint stroke() = abort("not today")
```

Please react with :+1: to this comment if you support this proposal.

**Comment by ghallak** [comment]
**Proposal 1.1:** If we decide to go with **Proposal 1**, should we use `@impl `or `impl`

```
@impl entrypoint stroke() = abort("not today")
```
```
impl entrypoint stroke() = abort("not today")
```

Please react with :heart: to this comment if you support `@impl` or with :tada: if you support `impl`.

**Comment by ghallak** [comment]
**Proposal 1.2:** If we decide to go with **Proposal 1**, should we use `contract Cat is Strokable` or `contract Cat : Strokable`

Please react with :heart: to this comment if you support  `contract Cat is Strokable` or with :tada: if you support `contract Cat : Strokable`.

**Comment by ghallak** [comment]
**Proposal 2:** Write the implementations in a separate block inside the contract

```
contract interface Strokable =
  entrypoint stroke : () => unit

contract Cat =
  impl Strokable =
    entrypoint stroke() = abort("not today")
  entrypoint ...
```
Please react with :+1: to this comment if you support this proposal.

**Comment by ghallak** [comment]
**Proposal 3:** Write the implementations separately outside the contract

```
contract interface Strokable =
  entrypoint stroke : () => unit

contract Cat =
  entrypoint ...

impl Cat for Strokable =
  entrypoint stroke() = abort("not today")
```

Please react with :+1: to this comment if you support this proposal.

**Comment by UlfNorell** [comment]
Why do you want special syntax for the interface entrypoints? The most natural thing (looking at Java for instance), would be to just write
```
contract interface Strokable =
  entrypoint stroke : () => unit

contract Cat : Strokable =
  entrypoint stroke() = abort("not today")
```

**Comment by marc0olo** [comment]
> Why do you want special syntax for the interface entrypoints? The most natural thing (looking at Java for instance), would be to just write
> 
> ```
> contract interface Strokable =
>   entrypoint stroke : () => unit
> 
> contract Cat : Strokable =
>   entrypoint stroke() = abort("not today")
> ```

actually I agree on that and I see **Proposal 1** is fitting this mostly but additionally has the `@impl` annotation. actually I thought of `@impl` to be the same like `@Override` annotation in Java where you could also have the reverse check if it really implements an interface or not.

already commented here:
- https://github.com/aeternity/aesophia/issues/307#issuecomment-819415414

**Comment by thepiwo** [comment]
I think @ annotations shouldn't be part of logic, just information for other systems, e.g. as pragma.
The proposal of Ulf sounds fine, also Proposal 2 (with full implementation, instead of impl) sound good.

**Comment by UlfNorell** [comment]
If I'm not mistaken, the `@override` annotation in java is there to prevent errors where you misspell the name of a method in a super class and the compiler can't know if you meant to override it or just declare a new method. In this case, that's not an issue because if you define the `strokke` entrypoint instead of `stroke` you'd get an error from not having defined all the methods of the interface.

**Comment by marc0olo** [comment]
> If I'm not mistaken, the `@override` annotation in java is there to prevent errors where you misspell the name of a method in a super class and the compiler can't know if you meant to override it or just declare a new method.

I think it's used for both, superclasses and interfaces. but I am sometimes mixing things up and you might be correct 😅 

generally see this topic also closely related to contract inheritance but that's another kind of story.

**Comment by genievot** [comment]
Proposals **2** and **3** introduce a scaled approach to implement multiple interfaces without confusion.
Voted for **2**nd because **3**rd seems very separate from other basic languages (harder for traditional people to catch) but a much cleaner approach.

**Comment by hanssv** [comment]
I agree with Ulf, no need to introduce extra keywords - keep it simple 🙏

**Comment by the-icarus** [comment]
Also agree with @UlfNorell but would suggest to drop the `contract` prior to `interface`. Other languages also just use the single `interface` keyword to define an interface (e.g. Java,C#,Solidity). Why should we have `contract interface`?

**Comment by nikita-fuchs** [comment]
> Also agree with @UlfNorell but would suggest to drop the `contract` prior to `interface`. Other languages also just use the single `interface` keyword to define an interface (e.g. Java,C#,Solidity). Why should we have `contract interface`?

Absolutely agree with this one and the rest vouching for simplicity and no @ decorators.

```
 interface Strokable =
  entrypoint stroke : () => unit

contract Cat : Strokable =
  entrypoint stroke() = abort("not today")
```

One thing is an interface, the other thing is a contract. The contract uses the interface, that's it. Can we keep it simple please ? 🙏

**Comment by omar-saadoun** [comment]
@ghallak can we add @UlfNorell proposal to vote?

**Comment by marc0olo** [comment]
I think we already voted for it 😛 

personally I also agree with @the-icarus to just use the single keyword `interface`. not sure why `contract` should be put in front

**Comment by nikita-fuchs** [comment]
The idea is: 

Let's use `contract interface` for both inter contract calls and the "interfacing". Else if I want to create a contract equivalent to Strokable and call it, I need to do:

```
 interface Strokable =
  entrypoint stroke : () => unit

contract interface Strokable =
  entrypoint stroke : () => unit

contract Cat : Strokable =
  entrypoint strokeAnotherCat(cat : Strokable) = Cat.stroke()

```
So why not just reuse `contract interface` ?

**Comment by marc0olo** [comment]
if inter contract calls require the keywords `contract interface` for a specific reason this makes sense. if inter contract calls can also be established by just providing `interface` keyword I would prefer removing the need for `contract` keyword there.

but I am generally happy to have the feature at all :-) ... just personal opinion
