### ISSUE TITLE
In the 5.0 compiler, Balance is called with AEX9, and an error is reported

### ISSUE THREAD

**Issue by sunbx** [aeternity/aesophia#310]

**Comment by marc0olo** [comment]
Hi @sunbx, this is probably the wrong place for that. Please check out the repository of the AEX9 reference implementation: https://github.com/aeternity/aeternity-fungible-token

The contracts have been updated to be compatible with compiler versions >= 5.

If you want to compile old contract code to handle contract calls you need to use a compiler with version < 5.

You can close the issue.

**Comment by sunbx** [comment]
So previously deployed contracts can only be used with compilers smaller than 5?
Is the compiler incompatible? If so, adding AEX9 tokens to the exchange, they cannot possibly use different compilers to accommodate different contracts, AEX9 contracts should be fixed

**Comment by marc0olo** [comment]
it should also be possible to use an updated contract that is compatible to compiler version >=5 with already deployed contracts as far as I know. haven't tested yet.

but after Iris hardfork is active you need to use compiler >=5 and FATE_02 VM to create new contracts. so for every new AEX-9 token you need the updated contract anyway.
