### ISSUE TITLE
cannot produce ACI for contract interface

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aesophia#319]
I am wondering about getting the ACI for contract interfaces. how can a dev currently verify that a contract interface is valid? compiler responds `{"message":"No contract defined.\n","pos":{"col":0,"line":0},"type":"type_error"}` when trying to produce the ACI.

**Comment by marc0olo** [comment]
to be clear about that and avoid misunderstandings:
- in compiler versions prior to `5.0.0` we were able to compile interfaces
- now when trying to compile interfaces defined with `contract interface` they aren't compiled anymore with the error above
    - I mean the error message is clear, but shouldn't the compiler also compile the interfaces?

**Comment by marc0olo** [comment]
ok after some discussions with @thepiwo the compiler currently requires a main contract for some reason. so in order to be able to get the ACI for an interface we need to remove the `interface` declaration prior to sending the code to the compiler.

I don't like that but it's the only way to achieve what I want right now.

**Comment by ghallak** [comment]
@marc0olo Could you provide an example of how were you able to produce ACI for contract interface in the past and what is the workaround that you have to do now in order to produce it?

**Comment by marc0olo** [comment]
let's close this for now. I will re-open if I see a need
