### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by radrow** [aeternity/aesophia#331]
Sometimes things are wrong but not wrong enough to be rejected. The compiler should produce warnings for, but not limited to:

- shadowing
- unused functions
- dead code
- non-exhaustive patterns
- obviously wrong code (eg negative spends)
- unused includes
- unused `stateful` annotations

There should be options to turn them off/on separately, packages (`Wall`, `pedantic`) and option to turn them into type errors.

**Comment by ghallak** [comment]
Closed by https://github.com/aeternity/aesophia/pull/346
