### ISSUE TITLE
bit shifting over numbers

### ISSUE THREAD

**Issue by bogdan-manole** [aeternity/aesophia#337]
I'm trying to implement some similar contracts from uniswap into aesophia. There are a lot of bitwise operations there, like: left shift , right shift over integer types. I think it will be helpful if we could have functions as shl, shr, not over bits type and also some way to convert between int and bits.

**Comment by hanssv** [comment]
Adding built in bitwise operations in FATE/Sophia needs a protocol upgrade (a.k.a a hard fork) - in the meantime we add a standard library: #340

**Comment by hanssv** [comment]
Merged to the Ceres branch.
