### ISSUE TITLE
Way to add ACI hint about int size

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aesophia#351]
Integers in FATE are arbitrary-sized, but some environments have limitations regarding this. There are cases where enough to use 4-byte integers that are natively supported by most environments. I think it reasonable to be able to make an alias to int type with an ACI-only hint about its size. Using that, devtools would be able to generate contract interfaces that will improve the developer's experience by allowing to interact with native numbers when arbitrary-sized numbers are not necessary.

**Comment by radrow** [comment]
This should be handled by the SDK. We refrain from having any sort of information that may be false on the Sophia side.

**Comment by radrow** [comment]
> if a contract entrypoint returned a value decoded to 42, SDK can't be sure that it would be less

This is not true. It is SDK's role to parse data returned from an entrypoint, and I don't see a reason why this check could not be done during parsing. There are many algorithms to validate if a numerical literal fits within given range. Depending on the result, SDK should return either an `int` or whatever data structure pertains to representing bignums in the target language. There is no blame on the environment.

I don't like the idea of bounded integers in Sophia. It introduces nasty failing scenarios which we really want to avoid. Unbounded ints is one of the features of FATE that is considered quite an advantage over EVM.

**Comment by davidyuk** [comment]
>  I don't see a reason why this check could not be done during parsing.

It can be done while parsing and it would work well in case all numbers are less than 64 bits. But if we have an entrypoint returning the user balance it would be parsed to `bigint` in case the user has a lot of coins and `number` otherwise. This would make things fragile, and require additional testing. We had this before in node API wrapper and it is obviously a bad practice. The idea is to have a special mark telling SDK to don't parse balance as `number` even if it is less than 64 bits to have a consistent return value type for such endpoints.

The approach I'm trying in SDK now is to use `bigint` where necessary: to represent ae amounts, including gas prices. For other things like block height, amount of gas, and account's nonce I'm using plain `number`. This looks inconsistent with contract interactions where all numbers have to be `bigint`s currently.

> I don't like the idea of bounded integers in Sophia.

I'm fine if it won't be checked by Sophia, just pass it through to aci. It may be not limited to short ints, another use case is to mark the int field as containing Date, and then sdk can convert the timestamp to Date object while doing parsing.

**Comment by hanssv** [comment]
@davidyuk Can't this just be solved by a `type` definition:
```
contract C =
  type shortIntIPromise = int

  entrypoint f(s : shortIntIPromise) : shortIntIPromise =
    s * 42
```
And
```
$ ./aesophia_cli --create_stub_aci /tmp/bar.aes 
main contract C =
  type shortIntIPromise = int
  entrypoint f : (C.shortIntIPromise) => C.shortIntIPromise
```

That won't be checked in Sophia and it is part of the ACI?!

**Comment by davidyuk** [comment]
Yea, I get a similar idea while discussing and I'm planning to check it, thank you!
