### ISSUE TITLE
How I can deactivate a smart contract?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aesophia#369]
I've checked documentation at https://aeternity.com/aesophia/v6.1.0/, but can't find anything.

I know it exists on bytecode level:

> DEACTIVATE Mark the current contract for deactivation.

https://github.com/aeternity/protocol/blob/6734de2e4c7cce7e5e626caa8305fb535785131d/contracts/fate.md#description-of-operations

**Comment by hanssv** [comment]
It is not implemented in the VM - but the OP-code is reserved for future use:
```
-spec deactivate(_) -> no_return().
deactivate(EngineState) ->
    Protocol = aefa_engine_state:consensus_version(EngineState),
    case Protocol >= ?IRIS_PROTOCOL_VSN of
        true  -> aefa_fate:abort({op_not_implemented, deactivate}, EngineState);
        false -> exit({error, op_not_implemented_yet})
    end.
```
