### ISSUE TITLE
Error when trying to unify `(unit) => 'a` and `() => int`

### ISSUE THREAD

**Issue by ghallak** [aeternity/aesophia#370]
The following code shows an error unless `function f() : int`  is changed to `function f(_ : unit) : int`:

```
main contract Main =
    datatype y('a) = Y(unit => 'a)

    function f2() : int = 1

    entrypoint ss() =
        let yv : y(int) = Y(f2)
        ()
```

**Comment by UlfNorell** [comment]
That's expected. `(unit) => 'a` and `() => 'a` are different. The first is a function with one argument and the second a function with zero arguments. If you want to keep `f2` as it is you have to change `y` to `datatype y('a) = Y(() => 'a)`
