### ISSUE TITLE
Hole expressions

### ISSUE THREAD

**Issue by radrow** [aeternity/aesophia#391]
In Haskell and Scala there is an expression variant called "hole". It represents a yet-unimplemented expression that throws error on build. A nice feature of that is that it can be used to check what the typechecker expects in a given place:

```
entrypoint test(l) =
  List.head(List.map(???, l)) + 1 // note the question marks
```
```
Type error: found a hole of type 'a => int
```

I propose `???` as it doesn't clash with patterns

**Comment by hanssv** [comment]
Just what every newly converted Solidity developer wants/needs, right? 🤣
