### ISSUE TITLE
Typechecker crashes if Chain.create or Chain.clone are used without arguments

### ISSUE THREAD

**Issue by radrow** [aeternity/aesophia#393]
Repro:

```
contract C =
  entrypoint f() =
    let x = Chain.create
    123
```

Error is thrown by `occurs_check1` where `var_args` are not handled. This is invalid and references to both functions without application should be banned in `infer_expr`.

**Comment by ghallak** [comment]
@radrow Why ban the references to these functions without application, instead of treating them like other normal functions.

The following code is valid for example:

```
namespace Nsp =
    function f(x) = x + 1

contract C =
  entrypoint f() =
    let x = Nsp.f
    x(1) + 1
```

**Comment by radrow** [comment]
Inference of var args is unobvious and hardly useful
