### ISSUE TITLE
Is it possible to convert string or int to bytes?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aesophia#436]
https://docs.aeternity.com/aesophia/v7.0.1/sophia_stdlib/#bytes
I've found functions to convert bytes to int and string, but I can't find the reverse. Probably it is because int and string have dynamic size, but still. As a workaround, I've used strings to concatenate binary data.

**Comment by hanssv** [comment]
To follow up, it is only possible to do a little bit without changing FATE - I'll see if I can make a suggestion for Ceres instead...

**Comment by hanssv** [comment]
See #456
