### ISSUE TITLE
parent interfaces need to be explicitely implemented in the main contract

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aesophia#454]
I expected to be the parent interface indirectly known by the main contract. I am not sure if this is intended behavior to require it to be implemented explicitely.

I can't recall the case 100% right now, but I am pretty sure I experienced this.

assuming interface `A` inherits from `B`, I would still need to implement both, `A` and `B`, explicitely in the main contract.

**Comment by radrow** [comment]
Can you craft a minimal example?

**Comment by ghallak** [comment]
@marc0olo Are you talking about the case in [this example](https://github.com/aeternity/aesophia/blob/master/test/contracts/polymorphism_contract_interface_extends_interface.aes) where you have to explicitly redeclare the functions from the parent interface?

**Comment by marc0olo** [comment]
> @marc0olo Are you talking about the case in [this example](https://github.com/aeternity/aesophia/blob/master/test/contracts/polymorphism_contract_interface_extends_interface.aes) where you have to explicitly redeclare the functions from the parent interface?

yeah I think that describes it. is there a specific reason it is like that? I assume this is on purpose then (sorry, I didn't check the docs yet)

**Comment by radrow** [comment]
This is done on purpose for the sake of explicitness. Note that interfaces are entirely abstract and they don't provide implementation.
