### ISSUE TITLE
Ability to get the current network id

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aesophia#461]
I've checked https://docs.aeternity.com/aesophia/v7.1.0/ and didn't find anything like this.

It is useful in case we validate a signature including network id in a smart contract. In two cases
- we deploy the same source code in different networks and want to don't have signatures replayable between them
- in case a fork of blockchain happens with a different id we want signatures to be incompatible between contracts 

While the first use case can be solved by slightly adjusting a contract between deployments, the second can't unless there is a way to get the actual network id in runtime.

**Comment by hanssv** [comment]
Good idea - should be a straightforward addition!

Though it is consensus breaking (adding new operation) - so won't be available until Ceres
